name: Verify
on: 
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ls
        run: ls -la

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.X'
      - name: setup
        run: npm run setup:ci --if-present
      - name: npm install
        run: npm ci
      - name: ls node_modules
        run: ls -la ./node_modules
      - name: npm audit
        run: npm audit
        continue-on-error: true # XXX?

      - name: lint
        run: npm run lint

      - name: build
        run: npm run grunt:build
      - name: build.zip
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

      - name: electron-forge package
        run: npx electron-forge package      


  builds:
    if: github.ref == 'refs/heads/main'
    needs: build
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node: [16, 18]
    runs-on: ${{ matrix.os }}
    name: Build @ node:${{ matrix.node }}@${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: setup
        run: npm run setup:ci --if-present
      - name: npm install
        run: npm ci

      - name: build
        run: npm run build


  verify: # TODO? RENAME? validate?
    if: github.ref == 'refs/heads/main' # XXX?
    name: Verify
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup
        run: npm run setup:ci --if-present
      - name: npm install
        run: npm install
      - name: build.zip
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: ls
        run: ls # -la fails in windows

      - name: electron-forge make
        run: npm run make
# FIXME
#     - name: out.zip
#       uses: actions/upload-artifact@v3
#       with:
#         name: out
#         path: out

# FIXME
#     - name: playwright test
#       run: npx playwright test __tests__/playwright/app
#     - uses: actions/upload-artifact@v2
#       if: always()
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30


  Playwright:
    if: github.ref == 'refs/heads/main'
    name: 'HTTP(S)://*.playwright.dev/* tests'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: setup
      run: npm run setup:ci --if-present
    - name: npm install
      run: npm ci

    - name: playwright test
      run: npx playwright test __tests__/playwright/dev

# TODO disabled in playwright.config.js
#   - uses: actions/upload-artifact@v2
#     if: always()
#     with:
#       name: playwright-report
#       path: playwright-report/
#       retention-days: 30


  CodeQL:
#   if: github.ref == 'refs/heads/main' # TODO?
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    name: 'CodeQL: ${{ matrix.language }}'
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
    - name: build.zip
      uses: actions/download-artifact@v3
      with:
        name: build
        path: build

    - name: CodeQL
      uses: github/codeql-action/analyze@v2
