name: playwright
on:
  schedule:
    - cron: '* 0 * * *'
  push:
    branches:
      - main
      - master

jobs:
  playwright:
    name: 'HTTP(S)://*.playwright.dev/* tests'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: setup
      run: npm run setup:ci --if-present
    - name: npm install
      run: npm ci
    - name: playwright test
      run: npx playwright test __tests__/playwright/dev

# TODO disabled in playwright.config.js
#   - uses: actions/upload-artifact@v2
#     if: always()
#     with:
#       name: playwright-report
#       path: playwright-report/
#       retention-days: 30
