name: Continuous Integration
on: 
  push:
  schedule:
    - cron: '* 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.X'
      - name: ls
        run: ls

      - name: setup
        run: npm run setup:ci --if-present
      - name: npm install
        run: npm ci

      - name: lint
        run: npm run lint

      - name: build
        run: npm run grunt:build
      - name: build.zip
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

      - name: electron-forge package
        run: npx electron-forge package      


  builds:
    needs: build
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node: [16, 18]
    runs-on: ${{ matrix.os }}
    name: build @ node:${{ matrix.node }}@${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: setup
        run: npm run setup:ci --if-present
      - name: npm install
        run: npm ci

      - name: build
        run: npm run build


  verify: # TODO? RENAME? validate?
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: setup
        run: npm run setup:ci --if-present
      - name: npm install
        run: npm install
      - name: build.zip
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: ls
        run: ls

      - name: electron-forge make
        run: npm run make
# FIXME
#     - name: out.zip
#       uses: actions/upload-artifact@v3
#       with:
#         name: out
#         path: out

# FIXME
#     - name: playwright test
#       run: npx playwright test __tests__/playwright/app
#     - uses: actions/upload-artifact@v2
#       if: always()
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30
